nodeLinker: node-modules

npmAlwaysAuth: true

npmAuthToken: "${NPM_TOKEN}"

npmRegistries:
  "https://registry.npmjs.org":
    npmAlwaysAuth: true
    npmAuthToken: "${NPM_TOKEN}"

npmRegistryServer: "https://registry.npmjs.org"

npmScopes:
  fjell:
    npmAlwaysAuth: true
    npmAuthToken: "${NPM_TOKEN}"
    npmPublishRegistry: "https://registry.npmjs.org"
    npmRegistryServer: "https://registry.npmjs.org"
