steps:
  - name: "node:22"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        corepack enable &&
        yarn set version stable &&
        yarn install &&
        yarn run build &&
        yarn run test &&
        yarn npm publish --access public
    secretEnv: ["NPM_TOKEN"]
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_NUMBER/secrets/NPM_TOKEN/versions/latest
      env: "NPM_TOKEN"
timeout: "1600s"
options:
  logging: CLOUD_LOGGING_ONLY
